### PR TITLE
Add support for HOOMD 3

### PR DESCRIPTION
**Pull request by pabloferz**
This would require making sure that we get fully initialized `System` instances on the before creating `Sampler` objects, e.g. first running `hoomd.run(0)` in HOOMD v2 or `sim.run(0)` in HOOMD v3.

### CODE REVIEW

**Comment by InnocentBug** [comment]
First look is good.

But there is something wrong the includes via CMake.
I tried to install and cmake finishes fine.

But I get this compilation error.
```
In file included from /home/ludwig/git/hoomd-dlext/dlext/include/DLExt.h:9,
                 from /home/ludwig/git/hoomd-dlext/dlext/include/SystemView.h:7,
                 from /home/ludwig/git/hoomd-dlext/dlext/src/SystemView.cc:4:
/home/ludwig/git/hoomd-blue/install/hoomd/include/hoomd/GlobalArray.h:33:10: fatal error: cuda_runtime.h: No such file or directory
   33 | #include <cuda_runtime.h>
```

It might be my messed up cuda env, or something is wrong in cmake.

**Review by InnocentBug — APPROVED** [review]
This looks good to me.

I tested to install against my existing hoomd 2.9.X installation and it seems to work.
(apart from the changes needed in Pysages itself of course.)

**Comment by pabloferz** [comment]
I tested with a HOOMD 3 installation and with PySAGES and it work there as well. The only thing missing now is a new release of HOOMD with https://github.com/glotzerlab/hoomd-blue/pull/1388 included.

**Comment by InnocentBug** [comment]
Ok, sounds good.
Please don't force push updats on branches, I have already seen.
It makes it more difficult to keep track of what you are changing.

**Comment by pabloferz** [comment]
HOOMD-blue v3.5.0 has been released and includes the patches needed for this plugin to work. Should be good to go now.

**Review by InnocentBug — APPROVED** [review]

**Pull request merged**
